In [1]:
import numpy as np

In [3]:
X=np.array([[200,220,250],
         [68,79,105],
        [110,140,180],
          [80,85,90]
         ])

In [6]:
X*75

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [8]:
X = np.array([
    [50,60,25],
    [10,13,5],
    [40,70,52]
])

In [28]:
y = np.array([20,30,15])

In [27]:
np.dot(y,X)

array([1900, 2640, 1430])

In [34]:
np.array([60,13,70])@np.array([[20,30,15]]).T

array([2640])